# Copyright 2025 Snowflake Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
        files: \.py$|\.pyi$
      - id: ruff-format
        files: \.py$|\.pyi$
  - repo: local
    hooks:
      - id: license-headers
        name: Checks that all files have the required license headers
        entry: ./scripts/check_license_headers.py
        language: system
        always_run: true
        pass_filenames: false
        exclude: |
          (?x)
          ^streamlit_pivot_table/frontend/public/
          |^streamlit_pivot_table/frontend/node_modules/
          |^streamlit_pivot_table/frontend/package-lock\.json$
          |^streamlit_pivot_table/frontend/\.prettierrc$
          |^streamlit_pivot_table/frontend/\.env$
      - id: format-ts-js
        name: Checks that all JS/TS files are formatted correctly
        entry: bash -c 'cd streamlit_pivot_table/frontend && npm run format'
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Add license for all (S)CSS/JS(X)/TS(X) files
        files: \.(s?css|jsx?|tsx?)$
        args:
          - --comment-style
          - "/**| *| */"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
        exclude: |
          (?x)
          ^streamlit_pivot_table/frontend/public/
          |^streamlit_pivot_table/frontend/.yarn/
      - id: insert-license
        name: Add license for all Python files
        files: \.py$|\.pyi$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all HTML files
        files: \.html$
        args:
          - --comment-style
          - "<!--| | -->"
          - --license-filepath
          - scripts/license-template.txt
          - --fuzzy-match-generates-todo
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)
          ^streamlit_pivot_table/frontend/public
          |^NOTICES$
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        exclude: |
          (?x)
          |^NOTICES$
